# Generated by Django 5.1.1 on 2024-10-07 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0004_supplier_provider"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="provider",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="product",
        ),
        migrations.AddField(
            model_name="supplier",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="products.product",
                verbose_name="Продукт",
            ),
        ),
    ]
