# Generated by Django 5.1.1 on 2024-10-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("suppliers", "0005_remove_supplier_provider_remove_supplier_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supplier",
            name="product",
        ),
    ]
