# Generated by Django 5.1.1 on 2024-10-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_product_delete_article"),
        ("suppliers", "0006_remove_supplier_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="product",
            field=models.ManyToManyField(
                related_name="article", to="products.product", verbose_name="Товар"
            ),
        ),
    ]
