# Generated by Django 5.1.1 on 2024-10-07 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("suppliers", "0006_remove_supplier_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="suppliers.supplier",
                verbose_name="Поставщик",
            ),
        ),
    ]
