# Generated by Django 5.1.1 on 2024-10-07 18:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_supplier"),
        ("suppliers", "0006_remove_supplier_product"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Product",
            new_name="Article",
        ),
    ]
